site_name: Aleo Oracle documentation
site_url: https://docs.aleooracle.xyz
repo_url: https://github.com/zkportal/aleo-oracle-docs
repo_name: aleo-oracle-docs

site_description: 'Aleo Oracle documentation for a trustless and secure way to bridge the traditional web with Aleo blockchain'

nav:
  - index.md
  - About:
    - Overview: 'about/index.md'
    - Architecture: 'about/architecture.md'
  - 'Using the Oracle':
    - 'Getting started': 'guide/index.md'
    - 'Understanding Attestation Response': 'guide/understanding_response.md'
    - 'Encoding data for Aleo': 'guide/aleo_encoding.md'
    - 'Submitting data to the Oracle': 'guide/submit_attestation.md'
    - 'Oracle program': 'guide/oracle_program.md'
    - 'Self-hosted verifier': 'guide/hosting_verifier.md'
    - 'Accepted headers': 'guide/accepted_headers.md'
  - SDK:
    - Overview: 'sdk/index.md'
    - Errors: 'sdk/errors.md'
    - 'JS API': 'sdk/js_api.md'
    - 'Go API': 'sdk/go_api.md'

theme:
  name: material
  custom_dir: overrides
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    # - navigation.indexes
    - toc.follow
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: light blue
      accent: light blue

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: light blue
      accent: light blue

extra:
  version: 1.1.0
  variables:
    links:
      oracle_backend_repo:
      verification_backend_repo: https://github.com/zkportal/oracle-verification-backend
      aleo_encoder_repo: https://github.com/zkportal/aleo-oracle-encoding
      js_sdk_repo: https://github.com/zkportal/aleo-oracle-sdk-js
      go_sdk_repo: https://github.com/zkportal/aleo-oracle-sdk-go
    constants:
      attestation_text_size_limit: 4KB
      attestation_precision_limit: 12

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zkportal/aleo-oracle-sdk-js
      name: Aleo Oracle SDK for JS
    - icon: fontawesome/brands/github
      link: https://github.com/zkportal/aleo-oracle-sdk-go
      name: Aleo Oracle SDK for Go

# copyright: Copyright &copy; 2024 zkPortal

plugins:
  - privacy
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
  - markdownextradata

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - toc:
      permalink: '#'
  - pymdownx.snippets:
      check_paths: true
      auto_append:
        - includes/abbreviations.md
      base_path:
        - "."
        - "docs/snippets"
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      # auto_title: true # adds a title with the language name to the code block
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
